"""Impact numbers for the README and Devpost, computed from the data (nothing typed by hand).

Run from repo root after score.py:  .venv/bin/python src/impact.py
Writes outputs/stop_afternoon_trips.csv and outputs/impact_summary.md.

Terms: a "bus visit" is one scheduled stop time at a stop (one bus arriving), on the
representative Wednesday used for daily_trips. It is a proxy for how many people wait, not a
rider count. Shelter shares use OpenStreetMap, so "unknown" is reported next to "no shelter".
"""
import pandas as pd

from gtfs import ROOT, build_afternoon_trips, REP_DATE

OUT = ROOT / "outputs"


def pct(part, whole) -> float:
    return 100 * part / whole


def main() -> None:
    aft = build_afternoon_trips()
    aft.to_csv(OUT / "stop_afternoon_trips.csv", index=False)

    d = pd.read_csv(OUT / "scored_stops.csv", dtype={"stop_id": str})
    d = d.merge(aft, on="stop_id", how="left")
    d["afternoon_trips"] = d["afternoon_trips"].fillna(0)
    total = d["daily_trips"].sum()
    afternoon = d["afternoon_trips"].sum()

    top = d[d["rank"].notna() & (d["rank"] <= 20)]
    need = pd.read_csv(OUT / "shade_need.csv", dtype={"stop_id": str})
    need_ids = set(need.loc[need["top20_shade_need"].astype(str) == "True", "stop_id"])
    need20 = d[d.stop_id.isin(need_ids)]
    by_shelter = d.groupby("shelter_status")["daily_trips"].sum()
    ranked = d[d["rank"].notna()]

    lines = [
        "# Impact numbers (generated by src/impact.py, do not edit by hand)",
        "",
        f"Representative weekday: Wednesday {REP_DATE[:4]}-{REP_DATE[4:6]}-{REP_DATE[6:]} "
        "(RTS Spring 2026 GTFS). A bus visit is one scheduled bus arrival at a stop.",
        "",
        "## Sentences you can use",
        "",
        f"- On a typical weekday RTS makes {total:,.0f} bus visits to {len(d)} stops. "
        f"{pct(afternoon, total):.0f} percent of them fall between 11 am and 5 pm, the hottest part "
        "of the day, when our morning satellite data understates the heat.",
        f"- {pct(by_shelter.get('none', 0), total):.0f} percent of weekday bus visits are at stops "
        f"OpenStreetMap lists as having no shelter, and another "
        f"{pct(by_shelter.get('unknown', 0), total):.0f} percent are at stops with unknown shelter "
        f"status. Only {pct(by_shelter.get('sheltered', 0), total):.0f} percent are at stops it lists as sheltered.",
        f"- The 20 highest-priority stops get {top['daily_trips'].sum():,.0f} bus visits a weekday, "
        f"{pct(top['daily_trips'].sum(), total):.0f} percent of the system total, from "
        f"{pct(len(top), len(d)):.0f} percent of stops. "
        f"{pct(top['afternoon_trips'].sum(), top['daily_trips'].sum()):.0f} percent of those visits are "
        "in the 11 am to 5 pm window.",
        f"- The 20 stops that most lack shade (Stream A's shade-need list) get "
        f"{need20['daily_trips'].sum():,.0f} bus visits a weekday. Only "
        f"{len(set(top.stop_id) & need_ids)} stops appear on both top 20 lists, so the two lists point to different places.",
        "",
        "## Table",
        "",
        "| Measure | Value |",
        "|---|---|",
        f"| Stops in the data | {len(d)} |",
        f"| Ranked stops | {len(ranked)} |",
        f"| Weekday bus visits, all stops | {total:,.0f} |",
        f"| Of which 11 am to 5 pm | {afternoon:,.0f} ({pct(afternoon, total):.1f} percent) |",
        f"| Visits at stops with OSM shelter = none | {by_shelter.get('none', 0):,.0f} ({pct(by_shelter.get('none', 0), total):.1f} percent) |",
        f"| Visits at stops with shelter unknown | {by_shelter.get('unknown', 0):,.0f} ({pct(by_shelter.get('unknown', 0), total):.1f} percent) |",
        f"| Visits at stops with OSM shelter = sheltered | {by_shelter.get('sheltered', 0):,.0f} ({pct(by_shelter.get('sheltered', 0), total):.1f} percent) |",
        f"| Visits at the top 20 stops | {top['daily_trips'].sum():,.0f} ({pct(top['daily_trips'].sum(), total):.1f} percent) |",
        f"| Visits at the shade-need top 20 | {need20['daily_trips'].sum():,.0f} ({pct(need20['daily_trips'].sum(), total):.1f} percent) |",
        "",
        "## Read these with the limits",
        "",
        "- A bus visit is not a rider. It is the best public proxy for how many people wait.",
        "- Shelter shares depend on OpenStreetMap, which is partial. Unknown is not the same as none.",
        "- The schedule is the Spring 2026 feed and one representative Wednesday.",
        "- Afternoon here means scheduled bus times, not measured afternoon temperatures.",
        "",
    ]
    (OUT / "impact_summary.md").write_text("\n".join(lines))
    print("\n".join(lines[6:14]))


if __name__ == "__main__":
    main()
