"""How stable is the top 20 when the census numbers are uncertain?

Run from repo root after score.py:  .venv/bin/python src/stability.py
Writes outputs/ranking_stability.csv and outputs/ranking_stability.md.

ACS values are estimates with a margin of error (90 percent, published by the Census). Small
tracts have wide margins: the Reitz Union tract has 164 households and 30.5 percent no-vehicle
plus or minus 16.9 points. This script redraws each tract's no-vehicle share within its margin
1000 times, recomputes transit_dependence and the score with the same formula as score.py, and
counts how often each stop stays in the top 20.

Only census uncertainty is varied. Temperature, bus visits and shelter status are held fixed,
so this is a robustness check on ONE input, not a full error bar on the ranking. It does not
tune anything: the published ranking is unchanged.
"""
import json
import math

import numpy as np
import pandas as pd

from gtfs import ROOT

OUT = ROOT / "outputs"
N_DRAWS = 1000
SEED = 20260920  # fixed so the numbers in the README reproduce exactly
Z90 = 1.645       # ACS margins of error are at the 90 percent level


def tract_uncertainty() -> pd.DataFrame:
    """Per tract: households, no-vehicle share, and its standard error in percentage points."""
    raw = json.load(open(ROOT / "data" / "acs_alachua_tracts.json"))["data"]
    rows = []
    for geo, t in raw.items():
        e, er = t["B08201"]["estimate"], t["B08201"]["error"]
        n, x = e["B08201001"], e["B08201002"]
        if not n:
            continue
        p = x / n
        # Census formula for the MOE of a proportion (falls back to the ratio form if the
        # value under the square root is negative).
        v = er["B08201002"] ** 2 - p ** 2 * er["B08201001"] ** 2
        moe = math.sqrt(v if v > 0 else er["B08201002"] ** 2 + p ** 2 * er["B08201001"] ** 2) / n
        rows.append({"tract_geoid": geo.split("US")[-1], "households": int(n),
                     "pct_no_vehicle_est": 100 * p, "moe_pts": 100 * moe})
    return pd.DataFrame(rows)


def main() -> None:
    d = pd.read_csv(OUT / "scored_stops.csv", dtype={"stop_id": str, "tract_geoid": str})
    r = d[d["rank"].notna()].reset_index(drop=True)
    tr = tract_uncertainty().set_index("tract_geoid")
    r = r.join(tr, on="tract_geoid")
    base_top = set(r.loc[r["rank"] <= 20, "stop_id"])

    rng = np.random.default_rng(SEED)
    sigma = (r["moe_pts"] / Z90).to_numpy()
    est = r["pct_no_vehicle_est"].to_numpy()
    fixed = (r["lst_percentile"] * np.log1p(r["daily_trips"]) * r["shelter_multiplier"]).to_numpy()
    in_top = np.zeros(len(r))
    ranks = np.zeros((N_DRAWS, len(r)))
    overlap = []
    # one draw per TRACT (stops in a tract share the same census number)
    tract_ids = r["tract_geoid"].to_numpy()
    tracts = np.unique(tract_ids)
    t_est = tr.loc[tracts, "pct_no_vehicle_est"].to_numpy()
    t_sig = (tr.loc[tracts, "moe_pts"] / Z90).to_numpy()
    idx = np.searchsorted(tracts, tract_ids)
    for i in range(N_DRAWS):
        draw = np.clip(rng.normal(t_est, t_sig), 0, 100)[idx]
        lo, hi = draw.min(), draw.max()          # same min-max over ranked stops as score.py
        td = 0.5 + (draw - lo) / (hi - lo)
        score = fixed * td
        rk = (-score).argsort().argsort() + 1
        ranks[i] = rk
        top = rk <= 20
        in_top += top
        overlap.append(len(base_top & set(r.loc[top, "stop_id"])))

    r["pct_draws_in_top20"] = (100 * in_top / N_DRAWS).round(0)
    r["median_rank_simulated"] = np.median(ranks, axis=0)
    out = r.sort_values("rank")[["rank", "stop_id", "stop_name", "tract_geoid", "households",
                                 "pct_no_vehicle_est", "moe_pts", "pct_draws_in_top20",
                                 "median_rank_simulated"]].round(1)
    out.to_csv(OUT / "ranking_stability.csv", index=False)

    top20 = out.head(20)
    solid = int((top20.pct_draws_in_top20 >= 80).sum())
    small = tr[tr.moe_pts >= 15]
    lines = [
        "# How stable is the top 20? (generated by src/stability.py)",
        "",
        f"Census numbers are estimates with margins of error. We redrew every tract's no-vehicle share "
        f"within its margin {N_DRAWS} times and recomputed the ranking with the same formula.",
        "",
        f"- On average {np.mean(overlap):.1f} of the 20 published top stops stay in the top 20 "
        f"(range {min(overlap)} to {max(overlap)}).",
        f"- {solid} of the 20 stay in the top 20 in at least 80 percent of draws.",
        f"- {len(small)} of {len(tr)} tracts have a margin of error of 15 points or more on their "
        "no-vehicle share; they are small tracts, often campus tracts with few households.",
        f"- The tract with the most top-20 stops has {int(tr.loc[top20.tract_geoid.mode().iloc[0], 'households'])} "
        f"households and a margin of error of "
        f"{tr.loc[top20.tract_geoid.mode().iloc[0], 'moe_pts']:.1f} points.",
        "",
        "Only census uncertainty is varied. Temperature, bus visits and shelter status are held fixed, "
        "so this tests one input, not the whole ranking. The published ranking is unchanged.",
        "",
        "Per-stop numbers are in `outputs/ranking_stability.csv`.",
        "",
    ]
    (OUT / "ranking_stability.md").write_text("\n".join(lines))
    print("\n".join(lines[3:11]))
    print(top20[["rank", "stop_name", "households", "pct_no_vehicle_est", "moe_pts",
                 "pct_draws_in_top20", "median_rank_simulated"]].to_string(index=False))


if __name__ == "__main__":
    main()
